pyflakes - cobbler/cobblerd.py.
cobbler/cobblerd.py:24: 'socket' imported but unused
cobbler/cobblerd.py:27: 'SimpleXMLRPCServer' imported but unused
cobbler/cobblerd.py:28: 'glob' imported but unused
cobbler/cobblerd.py:29: '_' imported but unused
cobbler/cobblerd.py:30: 'xmlrpclib' imported but unused
cobbler/cobblerd.py:36: redefinition of unused 'utils' from line 32