pyflakes - cobbler/modules/install_pre_log.py.
cobbler/modules/install_pre_log.py:4: '_' imported but unused
cobbler/modules/install_pre_log.py:5: 'traceback' imported but unused
cobbler/modules/install_pre_log.py:6: 'cexceptions' imported but unused
cobbler/modules/install_pre_log.py:7: redefinition of unused 'os' from line 3
cobbler/modules/install_pre_log.py:7: 'os' imported but unused
cobbler/modules/install_pre_log.py:8: redefinition of unused 'sys' from line 2