pyflakes - cobbler/modules/scm_track.py.
cobbler/modules/scm_track.py:25: 'traceback' imported but unused
cobbler/modules/scm_track.py:26: 'from cobbler.cexceptions import *' used; unable to detect undefined names
cobbler/modules/scm_track.py:27: redefinition of unused 'os' from line 24
cobbler/modules/scm_track.py:28: redefinition of unused 'sys' from line 23
cobbler/modules/scm_track.py:30: 'module_loader' imported but unused
cobbler/modules/scm_track.py:89: local variable 'rc' is assigned to but never used