pyflakes - cobbler/modules/serializer_couch.py.
cobbler/modules/serializer_couch.py:27: 'glob' imported but unused
cobbler/modules/serializer_couch.py:28: 'traceback' imported but unused
cobbler/modules/serializer_couch.py:31: 'exceptions' imported but unused
cobbler/modules/serializer_couch.py:37: '_' imported but unused
cobbler/modules/serializer_couch.py:38: 'utils' imported but unused
cobbler/modules/serializer_couch.py:39: 'from cexceptions import *' used; unable to detect undefined names
cobbler/modules/serializer_couch.py:40: redefinition of unused 'os' from line 25
cobbler/modules/serializer_couch.py:40: 'os' imported but unused