pyflakes - cobbler/services.py.
cobbler/services.py:24: 'exceptions' imported but unused
cobbler/services.py:27: 'traceback' imported but unused
cobbler/services.py:28: 'string' imported but unused
cobbler/services.py:29: 'sys' imported but unused
cobbler/services.py:36: 'remote' imported but unused
cobbler/services.py:40: redefinition of unused 'os' from line 26
cobbler/services.py:243: local variable 'type' is assigned to but never used
cobbler/services.py:337: local variable 'rc' is assigned to but never used
cobbler/services.py:383: redefinition of unused 'remote' from line 36
cobbler/services.py:451: redefinition of unused 'sys' from line 29
cobbler/services.py:459: redefinition of unused 'sys' from line 29