pyflakes - cobbler/action_sync.py.
cobbler/action_sync.py:27: 'shutil' imported but unused
cobbler/action_sync.py:29: 'sys' imported but unused
cobbler/action_sync.py:30: redefinition of unused 'glob' from line 26
cobbler/action_sync.py:31: 'traceback' imported but unused
cobbler/action_sync.py:32: 'errno' imported but unused
cobbler/action_sync.py:34: 'from cexceptions import *' used; unable to detect undefined names
cobbler/action_sync.py:37: 'item_distro' imported but unused
cobbler/action_sync.py:38: 'item_profile' imported but unused
cobbler/action_sync.py:39: 'item_repo' imported but unused
cobbler/action_sync.py:40: 'item_system' imported but unused
cobbler/action_sync.py:41: 'Template' imported but unused