pyflakes - cobbler/modules/serializer_catalog.py.
cobbler/modules/serializer_catalog.py:32: 'traceback' imported but unused
cobbler/modules/serializer_catalog.py:41: '_' imported but unused
cobbler/modules/serializer_catalog.py:42: 'utils' imported but unused
cobbler/modules/serializer_catalog.py:43: 'from cexceptions import *' used; unable to detect undefined names
cobbler/modules/serializer_catalog.py:44: redefinition of unused 'os' from line 29