pyflakes - cobbler/modules/install_pre_clear_anamon_logs.py.
cobbler/modules/install_pre_clear_anamon_logs.py:26: '_' imported but unused
cobbler/modules/install_pre_clear_anamon_logs.py:27: 'traceback' imported but unused
cobbler/modules/install_pre_clear_anamon_logs.py:28: 'cexceptions' imported but unused
cobbler/modules/install_pre_clear_anamon_logs.py:34: redefinition of unused 'os' from line 25
cobbler/modules/install_pre_clear_anamon_logs.py:36: 'sys' imported but unused
cobbler/modules/install_pre_clear_anamon_logs.py:48: undefined name 'CX'
cobbler/modules/install_pre_clear_anamon_logs.py:50: local variable 'objtype' is assigned to but never used
cobbler/modules/install_pre_clear_anamon_logs.py:52: local variable 'ip' is assigned to but never used
cobbler/modules/install_pre_clear_anamon_logs.py:63: local variable 'e' is assigned to but never used