pyflakes - cobbler/utils.py
cobbler/utils.py:35: 'logging' imported but unused
cobbler/utils.py:36: redefinition of unused 'shutil' from line 31
cobbler/utils.py:37: 'tempfile' imported but unused
cobbler/utils.py:38: 'signal' imported but unused
cobbler/utils.py:39: 'from cexceptions import *' used; unable to detect undefined names
cobbler/utils.py:41: 'time' imported but unused