pyflakes - cobbler/modules/sync_post_restart_services.py.
cobbler/modules/sync_post_restart_services.py:4: 'traceback' imported but unused
cobbler/modules/sync_post_restart_services.py:5: 'cexceptions' imported but unused
cobbler/modules/sync_post_restart_services.py:6: redefinition of unused 'os' from line 3
cobbler/modules/sync_post_restart_services.py:6: 'os' imported but unused
cobbler/modules/sync_post_restart_services.py:7: redefinition of unused 'sys' from line 2
cobbler/modules/sync_post_restart_services.py:8: 'xmlrpclib' imported but unused
cobbler/modules/sync_post_restart_services.py:27: local variable 'manage_tftpd' is assigned to but never used