pyflakes - cobbler/utils.py.
cobbler/utils.py:51: redefinition of unused 'fiver' from line 46
cobbler/utils.py:52: redefinition of function 'md5' from line 47