Unbreak iPXE
Currently CobblerSvc does not implement settings() method. This breaks
iPXE: attempts to fetch an iPXE script from the Cobbler API result in
the following AttributeError:

  File "/var/www/cobbler/svc/services.py", line 89, in application
    cw = CobblerSvc(server="http://127.0.0.1:%s" % remote_port)
  File "/usr/lib/python3.6/site-packages/cobbler/services.py", line 50, in __init__
    self.dlmgr = download_manager.DownloadManager(self.collection_mgr)
  File "/usr/lib/python3.6/site-packages/cobbler/download_manager.py", line 35, in __init__
    self.settings = collection_mgr.settings()
  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/manager.py", line 98, in settings
    return self.api.settings()
  AttributeError: 'CobblerSvc' object has no attribute 'settings

This commit provides the missing method.