pyflakes - cobbler/modules/install_post_log.py.
cobbler/modules/install_post_log.py:24: '_' imported but unused
cobbler/modules/install_post_log.py:25: 'traceback' imported but unused
cobbler/modules/install_post_log.py:26: 'cexceptions' imported but unused
cobbler/modules/install_post_log.py:27: redefinition of unused 'os' from line 23
cobbler/modules/install_post_log.py:27: 'os' imported but unused
cobbler/modules/install_post_log.py:28: redefinition of unused 'sys' from line 22