pyflakes - cobbler/modules/serializer_mongodb.py.
cobbler/modules/serializer_mongodb.py:28: 'traceback' imported but unused
cobbler/modules/serializer_mongodb.py:29: 'exceptions' imported but unused
cobbler/modules/serializer_mongodb.py:35: '_' imported but unused
cobbler/modules/serializer_mongodb.py:36: 'utils' imported but unused
cobbler/modules/serializer_mongodb.py:37: 'from cexceptions import *' used; unable to detect undefined names
cobbler/modules/serializer_mongodb.py:38: redefinition of unused 'os' from line 26
cobbler/modules/serializer_mongodb.py:38: 'os' imported but unused
cobbler/modules/serializer_mongodb.py:115: local variable 'ctype' is assigned to but never used