pyflakes - cobbler/remote.py.
cobbler/remote.py:23: 're' imported but unused
cobbler/remote.py:23: 'sys' imported but unused
cobbler/remote.py:23: 'socket' imported but unused
cobbler/remote.py:28: redefinition of unused 'base64' from line 24
cobbler/remote.py:30: 'traceback' imported but unused
cobbler/remote.py:36: 'from cexceptions import *' used; unable to detect undefined names
cobbler/remote.py:47: redefinition of unused 'utils' from line 35
cobbler/remote.py:49: '_' imported but unused
cobbler/remote.py:315: local variable 't' is assigned to but never used
cobbler/remote.py:1056: local variable 'e' is assigned to but never used
cobbler/remote.py:1843: local variable 'validated' is assigned to but never used
cobbler/remote.py:1855: local variable 'validated' is assigned to but never used
cobbler/remote.py:2190: local variable 'before_systems' is assigned to but never used
cobbler/remote.py:2191: local variable 'before_repos' is assigned to but never used
cobbler/remote.py:2192: local variable 'before_images' is assigned to but never used
cobbler/remote.py:2213: local variable 'rc' is assigned to but never used
cobbler/remote.py:2657: local variable 'now' is assigned to but never used