pyflakes - cobbler/modules/manage_bind.py.
cobbler/modules/manage_bind.py:26: 'sys' imported but unused
cobbler/modules/manage_bind.py:27: 'glob' imported but unused
cobbler/modules/manage_bind.py:28: 'traceback' imported but unused
cobbler/modules/manage_bind.py:29: 'errno' imported but unused
cobbler/modules/manage_bind.py:34: 'from cexceptions import *' used; unable to detect undefined names
cobbler/modules/manage_bind.py:37: 'item_distro' imported but unused
cobbler/modules/manage_bind.py:38: 'item_profile' imported but unused
cobbler/modules/manage_bind.py:39: 'item_repo' imported but unused
cobbler/modules/manage_bind.py:40: 'item_system' imported but unused
cobbler/modules/manage_bind.py:44: 'from types import *' used; unable to detect undefined names
cobbler/modules/manage_bind.py:199: redefinition of unused 'sys' from line 26
cobbler/modules/manage_bind.py:260: local variable 'forward_zones' is assigned to but never used
cobbler/modules/manage_bind.py:261: local variable 'reverse_zones' is assigned to but never used
cobbler/modules/manage_bind.py:318: local variable 'forward_zones' is assigned to but never used
cobbler/modules/manage_bind.py:319: local variable 'reverse_zones' is assigned to but never used