pyflakes - cobbler/modules/manage_import_signatures.py.
cobbler/modules/manage_import_signatures.py:27: 'simplejson' imported but unused
cobbler/modules/manage_import_signatures.py:28: 'traceback' imported but unused
cobbler/modules/manage_import_signatures.py:31: 'from cexceptions import *' used; unable to detect undefined names
cobbler/modules/manage_import_signatures.py:34: 'item_distro' imported but unused
cobbler/modules/manage_import_signatures.py:35: 'item_profile' imported but unused
cobbler/modules/manage_import_signatures.py:37: 'item_system' imported but unused
cobbler/modules/manage_import_signatures.py:47: '_' imported but unused
cobbler/modules/manage_import_signatures.py:309: redefinition of unused 'distro' from line 41
cobbler/modules/manage_import_signatures.py:513: redefinition of unused 'distro' from line 41
cobbler/modules/manage_import_signatures.py:593: local variable 'dotrepo' is assigned to but never used