Image install doesn't define distro's arch
Got this error during image install.

- looking for Cobbler at http://puppet:80/cobbler_api
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/koan/app.py", line 1230, in get_data
    data = getattr(self.xmlrpc_server, "get_%s_for_koan" % what)(name)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1253, in request
    return self._parse_response(h.getfile(), sock)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1392, in _parse_response
    return u.close()
  File "/usr/lib64/python2.6/xmlrpclib.py", line 838, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: "<type 'exceptions.AttributeError'>:'NoneType' object has no attribute 'arch'">
Could not communicate with puppet:None