several pep8 fixes.
cobbler/api.py:30: redefinition of unused 'action_buildiso' from line 29
cobbler/autoinstall_manager.py:270: local variable 'server' is assigned to but never used
cobbler/autoinstall_manager.py:295: local variable 'failed' is assigned to but never used
cobbler/item_image.py:26: 'validate' imported but unused
cobbler/remote.py:46: 'validate' imported but unused
cobbler/validate.py:21: 'os' imported but unused