utils: initialize main_logger only when needed
If main_logger is initialized when utils is imported, httpd tries to
unnecessarily open the log for some URLs and this causes SELinux denials.
Offending URL example: http://cobbler/cblr/svc/op/ks/system/test1

Traceback (most recent call last):

  File "/usr/lib64/python2.7/site-packages/mod_python/importer.py", line 1537, in HandlerDispatch
    default=default_handler, arg=req, silent=hlist.silent)

  File "/usr/lib64/python2.7/site-packages/mod_python/importer.py", line 1202, in _process_target
    module = import_module(module_name, path=path)

  File "/usr/lib64/python2.7/site-packages/mod_python/importer.py", line 296, in import_module
    log, import_path)

  File "/usr/lib64/python2.7/site-packages/mod_python/importer.py", line 680, in import_module
    execfile(file, module.__dict__)

  File "/var/www/cobbler/svc/services.py", line 22, in <module>
    from cobbler.services import CobblerSvc

  File "/usr/lib/python2.7/site-packages/cobbler/services.py", line 36, in <module>
    import remote

  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 45, in <module>
    import api as cobbler_api

  File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 26, in <module>
    import config

  File "/usr/lib/python2.7/site-packages/cobbler/config.py", line 30, in <module>
    import item_distro as distro

  File "/usr/lib/python2.7/site-packages/cobbler/item_distro.py", line 25, in <module>
    import utils

  File "/usr/lib/python2.7/site-packages/cobbler/utils.py", line 116, in <module>
    main_logger = clogger.Logger()

  File "/usr/lib/python2.7/site-packages/cobbler/clogger.py", line 43, in __init__
    self.logfile = open(logfile, "a")

IOError: [Errno 13] Permission denied: '/var/log/cobbler/cobbler.log'