pyflakes - web/cobbler_web/views.py.
web/cobbler_web/views.py:2: 'Context' imported but unused
web/cobbler_web/views.py:32: 'distutils' imported but unused
web/cobbler_web/views.py:33: 'exceptions' imported but unused
web/cobbler_web/views.py:34: redefinition of unused 'time' from line 29