pyflakes - cobbler/modules/serializer_mysql.py
cobbler/modules/serializer_mysql.py:28: 'traceback' imported but unused
cobbler/modules/serializer_mysql.py:29: 'exceptions' imported but unused
cobbler/modules/serializer_mysql.py:36: '_' imported but unused
cobbler/modules/serializer_mysql.py:37: 'utils' imported but unused
cobbler/modules/serializer_mysql.py:38: 'from cexceptions import *' used; unable to detect undefined names
cobbler/modules/serializer_mysql.py:39: redefinition of unused 'os' from line 26
cobbler/modules/serializer_mysql.py:39: 'os' imported but unused
cobbler/modules/serializer_mysql.py:40: 'ConfigParser' imported but unused
cobbler/modules/serializer_mysql.py:131: local variable 'ctype' is assigned to but never used