pyflakes - cobbler/action_buildiso.py.
cobbler/action_buildiso.py:27: 'sys' imported but unused
cobbler/action_buildiso.py:28: 'traceback' imported but unused
cobbler/action_buildiso.py:29: redefinition of unused 'shutil' from line 26
cobbler/action_buildiso.py:33: 'from cexceptions import *' used; unable to detect undefined names
cobbler/action_buildiso.py:34: '_' imported but unused